version: '3.7'

services:
    db:
        restart: always
        image: postgres
        environment:
            POSTGRES_DB: "dtekportal"
            POSTGRES_PASSWORD: "$DB_PASSWORD"
        volumes:
            # Makes database data persist even if we restart/rebuild container
            - db_data:/var/lib/postgresql/data
    web:
        build: .
        restart: always
        env_file: .env
        depends_on:
            - db
        volumes:
            - ./logs:/logs
            - static:/code/staticfiles/
    proxy:
        image: nginx:1-alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        depends_on:
            - web
        volumes:
            - static:/usr/share/nginx/html:ro
            - ./site.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
    db_data:
    static:
